Repository IBM/ibm-metering-sender-operator, pull requests merged in 2020-07, with the labels that each got.

#1 Shatt init
  Makefile
  README.md
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  build/bin/entrypoint
  build/bin/user_setup
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/.githooks/pre-commit
  common/scripts/.githooks/pre-commit-check.sh
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/delete-csv.sh
  common/scripts/gobuild.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_meteringsenders_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_meteringsender_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/addtoscheme_operator_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/operator/group.go
  pkg/apis/operator/v1alpha1/common_spec.go
  pkg/apis/operator/v1alpha1/doc.go
  pkg/apis/operator/v1alpha1/meteringsender_types.go
  pkg/apis/operator/v1alpha1/register.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_meteringsender.go
  pkg/controller/controller.go
  pkg/controller/meteringsender/meteringsender_controller.go
  pkg/resources/containers.go
  pkg/resources/reconcile.go
  pkg/resources/utils.go
  tools.go
  version/version.go
Labels: approved, lgtm, size/XXL

#3 update command string
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#4 update ubi image to remediate VA scans
  Makefile
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/S

#5 push images to artifactory
  Makefile
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S
